Minorproject/crop_recommendation_system/CRS/urls.py
from django.contrib import admin
from django.urls import path
from CRS.views import *
app_name='CRS'

urlpatterns = [
    # path('',Landing,name='landing'),
    path('',Home,name='home'),

    # path('predction',Predict,name='predict'),
    # path('cyp',CropPredict,name='croppridict'),

    path('crop_recomend',Crop,name='crop_recomend'),
    path('crs',CropRecomend,name='croprecomend'),

    # path('fertilizier_recomend',Fertilizer,name='fertilizer_recomend'),
    # path('frs',FertilizerRecomend,name='fertilizerrecomend'),

    path('about', About,name='about'),
    path('contact', Contact,name='contact'),

    path('profile',Profile,name='profile'),
    path('profileupdate/<int:id>/', ProfileUpdate,name='profileupdate'),

    path('passwordupdate', PasswordUpdate , name='passwordupdate'),



    # Authentication 
    path('register', Register,name='register'),
    path('login', Login,name='login'),
    path('logout',Logout, name='logout'),
  
]

Minorproject/crop_recommendation_system/crop_recommendation_system/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from .import settings


urlpatterns = [
    path('',include('CRS.urls')),
    path('admin/', admin.site.urls),
]  + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

Minorproject/crop_recommendation_system/CRS/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .managers import CustomManager
# Create your models here.


class CustomUser(AbstractUser):
    GENDER_CHOICES = [
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other'),
    ]
    username = None
    email = models.EmailField("Email",unique=True, blank=False)
    phone = models.CharField(max_length=10, blank=False)
    gender = models.CharField(max_length=50, choices=GENDER_CHOICES, blank=False)
    image = models.ImageField(upload_to='images',null=True, blank=True)
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS= []

    objects = CustomManager()

    def __str__(self):
        return self.email

Minorproject/crop_recommendation_system/CRS/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.contrib.auth import get_user_model
User = get_user_model()
from django.contrib.auth import authenticate, login as auth_login , logout as auth_logout
import numpy as np
import pickle




# ====================== HOME PAGE =============================#
def Home(request):
    return render(request, 'home.html')







#======================= PREDICTION PAGE ========================#
def Predict(request):
    return render(request, 'production.html')


#====================== CROP PREDICT =========================== #
# Rfr = pickle.load(open('models/crop_production_Rfr.pkl','rb'))
# crop_production_encoder = pickle.load(open('models/crop_production_encoder.pkl','rb'))
# crop_producion_mx = pickle.load(open('models/crop_production_mx.pkl','rb'))


def CropPredict(request):
    # if request.method=='POST':
    #     State_name = (request.POST['state_name'])
    #     District_name = (request.POST['district_name'])
    #     Crop_year = int(request.POST['crop_year'])
    #     Season = (request.POST['season'])
    #     Crop = (request.POST['crop'])
    #     Area = float(request.POST['area'])
      

    #     # Create an array of the input features
    #     features = np.array([[ State_name, District_name,Crop_year, Crop, Season, Area]],dtype=object).astype(str)
    #     # Transform the features using the preprocessor

    #     transformed_features = crop_production_encoder.fit_transform(features)
    #     transformed_features = crop_producion_mx.fit_transform(transformed_features).reshape(1,-1)
    #     # Make the prediction
    #     predicted_yield = Rfr.predict(transformed_features.reshape(1,-1))
    #     result = predicted_yield[0]
    
    #     return render(request, 'prediction.html' , {'result': result})

    # else:
    #     pass
    pass













#=================== RECOMMENDATION PAGE =========================#
def Crop(request):
    return render(request, 'crop.html')


#====================== CROP RECOMMEND  ==========================#

crop_recommend_Lr = pickle.load(open('models/crop_recommend_Lr.pkl','rb'))

def CropRecomend(request):
    if request.method=='POST':
        N = int(request.POST['Nitrogen'])
        P = int(request.POST['Phosphorous'])
        K = int(request.POST['Potassium'])
        Temperature = float(request.POST['Temperature'])
        Humidity = float(request.POST['Humidity'])
        pH = float(request.POST['pH'])
        Rainfall = float(request.POST['Rainfall'])

        feature_list = [N,P,K,Temperature,Humidity,pH,Rainfall]
        # single_predict = np.array([feature_list]).reshape(-1,1)
        prediction = crop_recommend_Lr.predict([feature_list])

        crop_dict = {0:'apple', 1:'banana', 2:'blackgram', 3:'chickpea', 4:'coconut', 5:'coffee',
       6:'cotton', 7:'grapes', 8:'jute', 9:'kidneybeans', 10:'lentil', 11:'maize',
       12:'mango', 13:'mothbeans', 14:'mungbean', 15:'muskmelon', 16:'orange', 17:'papaya',
       18:'pigeonpeas', 19:'pomegranate', 20:'rice', 21:'watermelon'}

        if prediction[0] in crop_dict:
            crop = crop_dict[prediction[0]]
            result ="{} is the best crop to be cultivated ".format(crop)
        else:
            result = "Sorry are not able to recommend a proper crop for this environment"

        return render(request, 'crop.html',{'result':result})
    else:
        pass

#============== CROP RECOMMENDATION PAGE END ================#







#=================== FERTILIZER PAGE =========================#
def Fertilizer(request):
    return render(request, 'fertilizer.html')


#====================== FERTILIZER RECOMMEND  ==========================#

# fertilizer_recommend = pickle.load(open('models/fertilizer.pkl','rb'))
# fertilizer_encoding = pickle.load(open('models/fertilizer_encode.pkl','rb'))

def FertilizerRecomend(request):
    # if request.method=='POST':
    #     Temparature = int(request.POST['temparature'])
    #     Humidity = int(request.POST['humidity'])
    #     Moisture = int(request.POST['moisture'])
    #     Soil_Type = request.POST['soil_type']
    #     Crop_Type = request.POST['crop_type']
    #     Nitrogen = int(request.POST['nitrogen'])
    #     Potassium = int(request.POST['potassium'])
    #     Phosphorous = int(request.POST['phosphorous'])

    #    # Create input array
    #     feature_list = np.array([[Temparature, Humidity, Moisture, Soil_Type,Crop_Type, Nitrogen, Potassium, Phosphorous]],dtype=object)

    #     # feature_list['Soil_Type'] = fertilizer_encoding.transform(feature_list['Soil_Type'])
    #     # feature_list['Crop_Type'] = fertilizer_encoding.transform(feature_list['Crop_Type'])

    #     feature_list = fertilizer_encoding.transform(feature_list)

    #     prediction = fertilizer_recommend.predict([feature_list]).reshape(1,-1)

    #     fertilizer_dict = {0:'10-10-10', 1:'10-26-26', 2:'14-14-14', 3:'14-35-14', 4:'15-15-15', 5:'17-17-17',
    #    6:'20-20', 7:'28-28', 8:'DAP', 9:'Potassium chloride', 10:'Potassium sulfate.', 11:'Superphosphate',
    #    12:'TSP', 13:'Urea'}

    #     if prediction[0] in fertilizer_dict:
    #         fertilizer = fertilizer_dict[prediction[0]]
    #         result ="{} is the best fertilizer to be cultivated ".format(fertilizer)
    #     else:
    #         result = "Sorry are not able to recommend a proper fertilizer for this environment"

    #     return render(request, 'fertilizer.html',{'result':result})
    # else:
        pass

#============== FERTILIZER RECOMMENDATION PAGE END ================#











#======================= About PAGE ===========================#
def About(request):
    return render(request, 'about.html')

 
 #==================== CONTACT PAGE START ========================#
def Contact(request):
    return render(request, 'contact.html')



 #==================== PASSWORD UPDATE  START =====================#


# User = get_user_model()  # Get your custom user model

def PasswordUpdate(request):
    # user = get_object_or_404(User, id=id)  # Get the user by ID

    # if request.method == 'POST':
    #     old_password = request.POST.get('old_password')
    #     new_password = request.POST.get('new_password')
    #     confirm_password = request.POST.get('confirm_password')

    #     # Check if the old password is correct
    #     if user.check_password(old_password):
    #         # Check if new password and confirm password match
    #         if new_password == confirm_password:
    #             user.set_password(new_password)  # Set and hash the new password
    #             user.save()  # Save the user with the new password
    #             return HttpResponse('Password changed successfully!')
    #         else:
    #             return HttpResponse('New password and confirm password do not match.')
    #     else:
    #         return HttpResponse('Old password is incorrect.')

    return render(request, 'password_update.html')







# ==================== PROFILE PAGE START =========================#

def Profile(request):
    if request.user.is_authenticated:
        return render(request,'profile.html')
    else:
        return redirect('/login')
    



#=================== PROFILE UPDATE ==============================#


 # Assuming you are using Django's default User model

def ProfileUpdate(request, id):
    user = get_object_or_404(User, id=id)  # Fetch the existing user object

    if request.method == 'POST':
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        phone = request.POST.get('phoneNumber')
        email = request.POST.get('email')
        image = request.FILES.get('image')  # Fetch image from request.FILES

        # Update user fields if provided in the form
        if fname:
            user.first_name = fname
        if lname:
            user.last_name = lname
        if phone:
            user.phone = phone
        if email:
            user.email = email
        if image:
            user.image = image 

        user.save()  
        messages.success(request,"Your Profile update Successfully")
        return redirect('/profile')

    return render(request, 'profile_update.html', {'user': user}) 







 
 #=========== REGISTER PAGE ===========================#
def Register(request):
    # check user is already register
    if request.user.is_authenticated:
        return redirect('/')

    if request.method == 'POST':
        fname = request.POST['fname'] 
        lname = request.POST['lname'] 
        phone = request.POST['phoneNumber']
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirmPassword']
        # gender = request.POST['gender']
       
        phone_check = User.objects.filter(phone=phone).exists()
        email_check = User.objects.filter(email=email).exists()


        if phone_check == True:
            messages.error(request,'Phone number already exists')
            return redirect('/register')

        elif email_check == True:
            messages.error(request,'Email already exists')
            return redirect('/register')
 
        elif len(phone) != 10:
            messages.error(request,'Number should be 10 Digit')
            return redirect('/register')
        
        elif password != confirm_password:
            messages.error(request,'Password & confirm password did not match.')
            return redirect('/register')

        else:
            user = User.objects.create_user(email=email,password=password,phone=phone)
            user.first_name = fname
            user.last_name = lname
            user.save()
            messages.success(request,"Your account successfully created")
            return redirect('/register')
            
    return render(request,'register.html')

Minorproject/crop_recommendation_system/CRS/templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="crop Recommendation system, yield predction, crop rediction , " />
    <meta name="description" content="Welcome to Crop Recommendation System to recommend best suitable crop for cultivation." />
    
    <!-- Title  -->
    <title>Crop Recommendation System</title>

    <link rel="stylesheet" href="{% static 'css/auth.css'%}">
    <link rel="stylesheet" href="{% static 'css/styles.css'%}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.2.0/js/bootstrap.min.js">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Favicon icon  -->
    <!-- <link id='favicon' rel="shortcut icon" href="{% static 'images/logo.png'  type="image/x-png %}">
    <title>Crop Recommendation System</title> -->
</head>

<style>
    .alert-error{
          background-color: rgb(230, 191, 191);
        }
        .alert.success{
          background-color: rgb(152, 228, 152);
        }
       
</style>
<body>

    <!-- Navigation Bar -->
    <header>
        <div class="container-fluid">
        <nav class="navbar">
            <div class="logo">
                <a href="{% url 'CRS:home' %}"><image id="logo" src="{% static 'images/logo.png' %}"></image></a>
            </div>
            <ul class="nav-links">
                <li><a href="{% url 'CRS:home' %}" class="active-link">Home</a></li>
               
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'CRS:crop_recomend' %}" class="active-link">Recommend</a></li>
                {% else %}
                <li><a href="/login">Recommend</a></li>
                {% endif%}
                <li><a href="{% url 'CRS:about' %}" class="active-link">About</a></li>
                <li><a href="{% url 'CRS:contact' %}" class="active-link">Contact</a></li> 
                {% if request.user.is_authenticated %}
                <li>
                    <i class="fa-solid fa-user usericon" ></i>
                    <a href="profile" >{{user.first_name}}</a>
                </li>
                <a class="button" href="logout" >Logout</a>
                {% else %}
                <a class="button" href="login" >Login</a>
                <a class="button" href="register" >Register</a>
                {% endif%}
               
            </ul>
            
           
            <div class="hamburger">
                <span class="bar"></span>
                <span class="bar"></span>
                <span class="bar"></span>
            </div>
        </nav>
        </div>
    </header>






    {% block content %}
  
    {% endblock %}




    
<!-- =============  FOOTER START ====================== -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-sm-6">
                <div class="single-box">
                    <img src="{% static 'images/logo.png' %}" alt="">
                <p>A crop recommendation system is an agricultural technology that leverages data and machine learning to suggest the most suitable crops for a particular region, improving productivity and sustainability.</p>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="single-box">
                    <h2>links</h2>
                <ul>
                    <li><a href="{% url 'CRS:about' %}">About US</a></li>
                    <li><a href="{% url 'CRS:contact' %}">Contact US</a></li>
                    <li><a href="{% url 'CRS:crop_recomend' %}">Crop Recommendation</a></li>
                    <li><a href="#">Privacy policy</a></li>
                    <li><a href="#">Terms & conditions</a></li>
           
                </ul>
                </div>                    
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="single-box">
                    <h2>Contact US</h2>
                <ul class="ul">
                    <li>
                        <p>
                            <i class="fa-solid fa-location-dot"></i>
                            Address: 42 Indrapui sector C, Raisen road, Bhopal, pin:462022
                        </p>
                        
                       
                    <li>
                        <p>
                            <i class="fa-solid fa-phone"></i>
                            Phone: +919755983112
                        </p>
                    </li>
                    <li>
                        <p>
                            <i class="fa-solid fa-envelope"></i>
                            Email: amansahu47388@gmail.com 
                        </p>
                    </li>
                    
                </ul>
                </div>                    
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="single-box">
                    <h2>Newsletter</h2>
                    <p>Subscribe to our newsletter for expert guidance tailored to your agricultural needs!</p>
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="Recipient's username" aria-label="Enter your Email ..." aria-describedby="basic-addon2">
                        <span class="input-group-text" id="basic-addon2"><i class="fa fa-long-arrow-right"></i></span>
                    </div>
                    <h2>Follow us on</h2>
                    <p class="socials">
                        <a href="https://github.com/dashboard"><i class="fa-brands fa-github"></i></a>
                        <a href="https://www.instagram.com/"><i class="fa-brands fa-instagram"></i></a>
                        <a href="https://www.linkedin.com/feed/"><i class="fa-brands fa-linkedin-in"></i></a>
                        <a href="https://x.com/home"><i class="fa-brands fa-x-twitter"></i></a>
                    </p>
                </div>
            </div>
        </div><hr>
    </div>
    <div class="footer-copyright">
        <p>
            All Rights Reserved. &copy; 2024 <a>crop Recommendation system</a> Design By: Aman sahu
        </p>
    </div>
</footer>




<!-- ======================   FOOTER END ===================== -->
  



     





    <script src="{% static 'js/script.js'%}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
   
</body>
</html>

Minorproject/crop_recommendation_system/CRS/templates/password_update.html
{% extends 'main.html'%}
{% load static %}


{% block content %}


<div class="profile-container">
    <div class=" light-style flex-grow-1 container-p-y">
        <h3 class="font-weight-bold py-3 mb-4">
            Account settings
        </h3>
        <div class="card overflow-hidden">
            <div class="row no-gutters row-bordered row-border-light">
                <div class="col-md-3 pt-0">
                    <div class="list-group list-group-flush account-settings-links">
                        <a class="list-group-item list-group-item-action active" data-toggle="list"
                            href="{% url 'CRS:profile' %}">Profile</a>
                        <a class="list-group-item list-group-item-action" data-toggle="list"
                            href="{% url 'CRS:passwordupdate' %}">Change password</a>  
                        <a class="list-group-item list-group-item-action" data-toggle="list"
                            href="{% url 'CRS:logout' %}">
                        Logout</a> 
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="tab-content">
                        <div class="tab-pane fade active show" id="account-general">
                            <div class="card-body pb-2">
                            <form action="" method="post">
                                <div class="form-group">
                                    <label class="form-label">Old password</label>
                                    <input type="password" name="old_password" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label class="form-label">New password</label>
                                    <input type="password" name="new_password" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label class="form-label">Repeat new password</label>
                                    <input type="password" name="confirm_password" class="form-control">
                                </div>
                                <div class="text-center mt-3">
                                    <button type="button" class="btn btn-success profile-save">Save changes</button>&nbsp;
                                    <button type="button" class="btn btn-default">Cancel</button>
                                </div>
                            </form>    
                        </div>                 
                    </div>
                </div>
            </div>
        </div>
        
    </div>
</div>





{% endblock %}

Minorproject/crop_recommendation_system/CRS/templates/profile.html
{% extends 'main.html'%}
{% load static %}


{% block content %}

{% for message in messages %}
      <div id="message" >
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
           {{message}}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      </div>
      {% endfor %}

<div class="profile-container">
    <div class=" light-style flex-grow-1 container-p-y">
        <h3 class="font-weight-bold py-3 mb-4">
            Account settings
        </h3>
        <div class="card overflow-hidden">
            <div class="row no-gutters row-bordered row-border-light">
                <div class="col-md-3 pt-0">
                    <div class="list-group list-group-flush account-settings-links">
                        <a class="list-group-item list-group-item-action active"  data-toggle="list"
                            href="{% url 'CRS:profile' %}">Profile</a>
                        <a class="list-group-item list-group-item-action" data-toggle="list"
                            href="{% url 'CRS:passwordupdate' %}">Change password</a>
                        <a class="list-group-item list-group-item-action" data-toggle="list"
                            href="{% url 'CRS:logout' %}">
                        Logout</a>
                       
                       
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="tab-content">
                        <div class="tab-pane fade active show" id="account-general">
                            <div class="card-body media ">
                                {% if user.image %}
                                <img src="{{user.image.url}}" alt="" class="d-block ui-w-80">
                                {% else %}
                                <img src="" alt="" class="d-block ui-w-80">
                                {% endif %}

                               
                            
                                <div class="media-body ">
                    
                                    <a href="{% url 'CRS:profileupdate' user.id %}" class="btn btn-outline-success">
                                        <i class="fa-solid fa-user-pen"></i>
                                        Edit Profile
                                    </a> &nbsp;

                                </div>
                            </div>
                         
                            <hr class="border-light m-0">
                            <div class="card-body">
                                <div class="form-group">
                                    <label class="form-label">First Name</label>
                                    <input disabled class="form-control " value="{{ user.first_name }}" name="fname">
                                </div>
                                <div class="form-group">
                                    <label class="form-label">Last Name</label>
                                    <input disabled class="form-control" value="{{user.last_name}}" name="lname">
                                </div>
                                <div class="form-group">
                                    <label class="form-label">Phone number</label>
                                    <input disabled class="form-control" value="{{user.phone}}">
                                </div>
                                <div class="form-group">
                                    <label class="form-label">E-mail</label>
                                    <input disabled class="form-control mb-1" value="{{user.email}}">
                                    
                                </div>
                                <div class="form-group">
                                    <label class="form-label">Gender</label>
                                    <input disabled class="form-control" value="{{user.gender}}" name="gender">
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>





{% endblock %}

Minorproject/crop_recommendation_system/CRS/templates/profile_update.html
{% extends 'main.html'%}
{% load static %}


{% block content %}


<div class="profile-container">
    <div class=" light-style flex-grow-1 container-p-y">
        <h3 class="font-weight-bold py-3 mb-4">
            Account settings
        </h3>
        <div class="card overflow-hidden">
            <div class="row no-gutters row-bordered row-border-light">
                <div class="col-md-3 pt-0">
                    <div class="list-group list-group-flush account-settings-links">
                        <a class="list-group-item list-group-item-action active"  data-toggle="list"
                            href="{% url 'CRS:profile' %}">Profile</a>
                        <a class="list-group-item list-group-item-action" data-toggle="list"
                            href="{% url 'CRS:passwordupdate' %}">Change password</a>
                        <a class="list-group-item list-group-item-action" data-toggle="list"
                            href="{% url 'CRS:logout' %}">
                        Logout</a>
                       
                       
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="tab-content">
                        <div class="tab-pane fade active show" id="account-general">
                           
        
                            <hr class="border-light m-0">
                            <div class="card-body">
                            <form action="/profileupdate/{{user.id}}/" method="post" enctype="multipart/form-data"> 
                                {% csrf_token %}
                                <div class="form-group">
                                    <label class="form-label">First Name</label>
                                    <input type="text" class="form-control " value="{{ user.first_name }}"  name="fname">
                                </div>
                                <div class="form-group">
                                    <label class="form-label">Last Name</label>
                                    <input type="text" class="form-control" value="{{user.last_name}}"  name="lname">
                                </div>
                                <div class="form-group">
                                    <label class="form-label">Phone number</label>
                                    <input type="text" class="form-control"  value="{{user.phone}}" name="phone">
                                </div>
                                <div class="form-group">
                                    <label class="form-label">E-mail</label>
                                    <input  class="form-control"  value="{{user.email}}" name="email">
                                    
                                </div>
                                <div class="form-group">
                                    <label class="form-label">Gender</label>
                                    <input type="text" class="form-control" value="{{user.gender}}"  name="gender">
                                </div>
                                <div class="form-group">
                                    <label class="form-label">Profile image</label>
                                    <input type="file" class="form-control"   name="image">
                                </div>
                                <input type="submit" class="btn btn-success Update-profile " value="Save Changes">
                               
                            </form>    
                            </div>


                        </div>
                        <div class="tab-pane fade" id="account-change-password">
                            <div class="card-body pb-2">
                                <div class="form-group">
                                    <label class="form-label">Current password</label>
                                    <input type="password" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label class="form-label">New password</label>
                                    <input type="password" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label class="form-label">Repeat new password</label>
                                    <input type="password" class="form-control">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>





{% endblock %}